/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

/**
 *
 * @author User-Pc
 */
public class Hakkımızda extends javax.swing.JFrame {

    /**
     * Creates new form Hakkımızda
     */
    public Hakkımızda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jLabel1.setText("Bebek bölgesinde 2004 yılından beri hizmet veren Dermako Eczanesi, ilaç ve kişisel bakım alanlarında isteyebileceğiniz her ürün ve servisi bünyesinde bulundurmaktadır. Dermako Eczanesinin misyonu sağlık konusunda kaliteli ve doğru bilgilendirme ile sağlıkta ilk başvuru noktası olabilmektir. Butik anlayışın ön plana çıktığı bu eczanede gerektiğinde e-mail yolu ile hastaya bilgi aktarımı yapılabilmektedir. Dermako Eczanesine girdiğinizde ilk fark edebileceğiniz sıcak yaklaşım, bilgi paylaşımı, yönlendirme, çözüm üretme ve takip ile bütünleşerek eczaneyi mesleğin ciddiyetle yürütüldüğü seçkin bir mekân haline getirmektedir.");

        jScrollPane1.setViewportView(jTextPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bebek bölgesinde 2004 yılından beri hizmet veren Dermako Eczanesi, ilaç ve kişisel bakım alanlarında isteyebileceğiniz her ürün ve servisi bünyesinde bulundurmaktadır. Dermako Eczanesinin misyonu sağlık konusunda kaliteli ve doğru bilgilendirme ile sağlıkta ilk başvuru noktası olabilmektir. Butik anlayışın ön plana çıktığı bu eczanede gerektiğinde e-mail yolu ile hastaya bilgi aktarımı yapılabilmektedir. Dermako Eczanesine girdiğinizde ilk fark edebileceğiniz sıcak yaklaşım, bilgi paylaşımı, yönlendirme, çözüm üretme ve takip ile bütünleşerek eczaneyi mesleğin ciddiyetle yürütüldüğü seçkin bir mekân haline getirmektedir.");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setText("Bebek bölgesinde 2004 yılından beri hizmet veren Dermako Eczanesi, ilaç ve kişisel bakım alanlarında isteyebileceğiniz her ürün ve servisi bünyesinde bulundurmaktadır. Dermako Eczanesinin misyonu sağlık konusunda kaliteli ve doğru bilgilendirme ile sağlıkta ilk başvuru noktası olabilmektir. Butik anlayışın ön plana çıktığı bu eczanede gerektiğinde e-mail yolu ile hastaya bilgi aktarımı yapılabilmektedir. Dermako Eczanesine girdiğinizde ilk fark edebileceğiniz sıcak yaklaşım, bilgi paylaşımı, yönlendirme, çözüm üretme ve takip ile bütünleşerek eczaneyi mesleğin ciddiyetle yürütüldüğü seçkin bir mekân haline getirmektedir.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("HAKKIMIZDA");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Bebek bölgesinde 2004 yılından beri hizmet veren Dermako Eczanesi, ilaç ve kişisel \nbakım alanlarında isteyebileceğiniz her ürün ve servisi bünyesinde bulundurmaktadır. \nDermako Eczanesinin misyonu sağlık konusunda kaliteli ve doğru bilgilendirme ile sağlıkta\n ilk başvuru noktası olabilmektir. Butik anlayışın ön plana çıktığı bu eczanede gerektiğinde \ne-mail yolu ile hastaya bilgi aktarımı yapılabilmektedir.Dermako Eczanesine girdiğinizde ilk \nfark edebileceğiniz sıcak yaklaşım, bilgi paylaşımı, yönlendirme, çözüm üretme ve takip ile \nbütünleşerek eczaneyi mesleğin ciddiyetle yürütüldüğü seçkin bir mekân haline getirmektedir\n.Ayrıca eczanede ücretsiz cilt bakımı, makyaj, yağ ve kilo ölçümü yapılmaktadır.\nDermako'da akıcı bir İngilizce ile yabancılara da aynı derecede bilgi ve servis verilebilmektedir.");
        jScrollPane3.setViewportView(jTextArea2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/drug.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/previous.png"))); // NOI18N
        jMenu1.setText("Geri");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        KayıtVeGiris k=new KayıtVeGiris();
        k.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
