/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User-Pc
 */
public class IlacSatıs extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    private String kullaniciAdi = "root";
    private String parola = "";
    private String host = "localhost";
    private String dtb = "hasta";
    private int port = 3306;
    private Connection conn = null;

    /**
     * Creates new form IlacSatıs
     */
    public IlacSatıs(String ad, String tcNo) {
        initComponents();

        adSoyad_field.setText(ad);
        tcNo_field.setText(tcNo);
        setRecordsToTable();

    }

    public IlacSatıs() {
        initComponents();
        setRecordsToTable();

    }

    public void setRecordsToTable() {
     
       //Sayfa açılır açılmaz tablonun dolu olduğu gözükmesi için bu metodu constructora ekledim. 
        String url = "jdbc:mysql://" + this.host + ":" + this.port + "/" + this.dtb + "?useUnicode=true&characterEncoding=utf8";
        baglan();
        try {
            conn = DriverManager.getConnection(url, kullaniciAdi, parola);
            PreparedStatement pst = conn.prepareStatement("select * from ilacsatisi");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String tcNo = rs.getString("tc");
                String adSoyad = rs.getString("Ad_Soyad");
                String ilacAdi = rs.getString("ilacAdı");
                int doz = rs.getInt("ilacDozu");
                String fiyat = rs.getString("fiyat");
//Buradaki bilgileri alıp table 'ın satırlarına yazıyor.
                Object[] obj = {tcNo, adSoyad, ilacAdi, doz, fiyat};
                tableModel = (DefaultTableModel) ilacSatısTablosu.getModel();
                tableModel.addRow(obj);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ilacFiyati_field = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tcNo_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adSoyad_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ilac_comboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        doz_spinner = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ilacSatısTablosu = new javax.swing.JTable();
        ilacLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        kaydet_button = new javax.swing.JButton();
        ara_field = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        guncel_button = new javax.swing.JButton();
        sil_btn = new javax.swing.JButton();
        ilacFiyat_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setText("İLAÇ SATIŞ SİSTEMİ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        jMenuItem1.setText("Geri");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Yazdır");
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Yenile");
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("İLAÇ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("SATIŞ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("SİSTEMİ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 0));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("T.C No");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ad Soyad");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("İlaç");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        ilac_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "AFINITOR® 5 mg tablet", "ALOMIDE® % 0.1 steril göz damlası", "AZARGA®", "AZOPT® %1 Steril Göz Damlası", "BETOPTIC® %0.5 Steril Göz Damlası", "BETOPTIC® S %0.25 Steril Göz Damlası", "CATAFLAM® 50 mg draje", "CERTICAN® 0.25 mg suda çözünür tablet", "CERTICAN® 0.75 mg tablet", "JAKAVI® ", "FLAREX®", " EXJADE® ", "EXFORGE®", " EXELON®" }));
        ilac_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilac_comboBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Doz");

        doz_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Fiyat");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        ilacSatısTablosu.setBackground(new java.awt.Color(102, 102, 0));
        ilacSatısTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "T.C No", "Ad Soyad", "İlaç Adı", "Doz", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ilacSatısTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ilacSatısTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ilacSatısTablosu);

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("E-REÇETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kaydet_button.setBackground(new java.awt.Color(51, 51, 0));
        kaydet_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kaydet_button.setText("KAYDET");
        kaydet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydet_buttonActionPerformed(evt);
            }
        });

        ara_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ara_fieldKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("KAYITLARI ARA");

        guncel_button.setBackground(new java.awt.Color(102, 102, 0));
        guncel_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guncel_button.setText("GÜNCELLE");
        guncel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncel_buttonActionPerformed(evt);
            }
        });

        sil_btn.setBackground(new java.awt.Color(102, 102, 0));
        sil_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sil_btn.setText("SİL");
        sil_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tcNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adSoyad_field, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(ilac_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(ilacLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doz_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(kaydet_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ilacFiyat_field, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(guncel_button)
                        .addGap(53, 53, 53)
                        .addComponent(sil_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(ara_field, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tcNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(adSoyad_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ilac_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(doz_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ilacFiyat_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ilacLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(58, 58, 58)
                .addComponent(ara_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sil_btn)
                    .addComponent(guncel_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydet_button)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 940, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/previous.png"))); // NOI18N
        jLabel12.setText("GERİ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        jPanel4.setBackground(new java.awt.Color(102, 102, 0));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/medicine.png"))); // NOI18N
        jLabel13.setText("İLAÇ LİSTELERİ");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 50));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
  
    String input=JOptionPane.showInputDialog(this, "Giriş için şifreyi yazınız","UYARI", JOptionPane.OK_CANCEL_OPTION);
       if(JOptionPane.OK_OPTION==0){
              İlacListesi ilacListe = new İlacListesi();
        ilacListe.setVisible(true);
        dispose();
        } 
        
        
    
    }//GEN-LAST:event_jLabel13MouseClicked
    public void ara(String kelime) {
        tableModel = (DefaultTableModel) ilacSatısTablosu.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(tableModel);
        ilacSatısTablosu.setRowSorter(trs);
        //Arama sonuçlarını filtrelemek için RowFilter kullandım.Kullanıcı yazdığında satırlar dinamik olarak süzülür.
        trs.setRowFilter(RowFilter.regexFilter(kelime));
    }
    private void ilac_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilac_comboBoxActionPerformed
        // TODO add your handling code here:
  //ilaçın adını combo boxtan alarak altındaki labela yazar
        Object obj = ilac_comboBox.getSelectedItem().toString();
        ilacLabel.setText((String) obj);
    }//GEN-LAST:event_ilac_comboBoxActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        //Fiyatı random bir şekilde atamak istedim sisteme.
        int random = (int) (Math.random() * 20);
        String fiyat = Integer.toString(random);
        ilacFiyat_field.setText(fiyat + "TL");

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        //Geri metodudur.Bir sonraki sayfaya gider.
        KayıtVeGiris kayitGiris = new KayıtVeGiris();
        kayitGiris.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Erecete sayfasını açar ve bilgileri constructor sayesinde bir sonraki sayfaya basar.
        EReceteGoruntule erecete = new EReceteGoruntule(tcNo_field.getText(), adSoyad_field.getText(), ilacFiyat_field.getText());
        erecete.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    DbBaglantiİlac baglanti = new DbBaglantiİlac();
    private void kaydet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydet_buttonActionPerformed
   //kaydet metodunun içine gerekli parametreler gönderilerek kayıt sağlanır.
        String tcNo = tcNo_field.getText();
        String adSoyad = adSoyad_field.getText();
        String ilac = ilacLabel.getText();
        int doz = (int) doz_spinner.getValue();
        String fiyat = ilacFiyat_field.getText();
        baglanti.kaydet(tcNo, adSoyad, ilac, doz, fiyat);
    }//GEN-LAST:event_kaydet_buttonActionPerformed

    private void ilacSatısTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilacSatısTablosuMouseClicked
        // Tabloya tıklanıldığında kişinin bilgileri yukarıdaki fieldlarda görünüyor.
        //Kaydet butonunu ve tc numarası değiştirilmez olması için Enable (False ) yapıldı.
        if (ilacSatısTablosu.getSelectedRow() < 0) {
            return;
        }

        String tcNo = (String) tableModel.getValueAt(ilacSatısTablosu.getSelectedRow(), 0);
        String url = "jdbc:mysql://" + this.host + ":" + this.port + "/" + this.dtb + "?useUnicode=true&characterEncoding=utf8";
        baglan();
        try {
            conn = DriverManager.getConnection(url, kullaniciAdi, parola);
            Statement stmt = conn.createStatement();
            String query = "select * from ilacsatisi WHERE tc=" + tcNo;
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                İlacGosterimi ig = new İlacGosterimi();
                ig.tc = rs.getString("tc");
                ig.ad = rs.getString("Ad_Soyad");
                ig.ilacAdi = rs.getString("ilacAdı");
                ig.doz = rs.getInt("ilacDozu");
                ig.fiyat = rs.getString("fiyat");

                tcNo_field.setText(ig.tc);
                adSoyad_field.setText(ig.ad);
                ilacLabel.setText(ig.ilacAdi);
                doz_spinner.setValue(ig.doz);
                ilacFiyati_field.setText(ig.fiyat);
                kaydet_button.setEnabled(false);
                tcNo_field.setEnabled(false);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_ilacSatısTablosuMouseClicked

    private void guncel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncel_buttonActionPerformed
     //Gerekli parametreleri guncelle metodunun içine yazdığımızda İlacın adını güncelliyor.
        String tc = tcNo_field.getText();
        String ad = adSoyad_field.getText();
        String ilac = ilacLabel.getText();
        int doz = (int) doz_spinner.getValue();

       baglanti.guncelle(tc, ad, ilac, doz);
    }//GEN-LAST:event_guncel_buttonActionPerformed

    private void sil_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_btnActionPerformed
     //Parametreleri sil metoduna yazınca silmek istediğimiz kişi siliniyor.
        String tc = tcNo_field.getText();
        String ad = adSoyad_field.getText();
        String ilac = ilacLabel.getText();
        int doz = (int) doz_spinner.getValue();
        baglanti.sil(tc, ad, ilac, doz);
        
    }//GEN-LAST:event_sil_btnActionPerformed

    private void ara_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ara_fieldKeyReleased
        // TODO add your handling code here:
        //ara metodunun içine textfielddaki kelimeyi gönderiyoruz.Baş harfini yazdığımız kişi çıkıyor.
        String kelimeAra = ara_field.getText();
        ara(kelimeAra);
    }//GEN-LAST:event_ara_fieldKeyReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        //İlacGoruntule sayfasını açıyor.
        İlacGoruntule iG = new İlacGoruntule(adSoyad_field.getText(), tcNo_field.getText());
        iG.setVisible(true);
        iG.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        // TODO add your handling code here:
        //Sağa tıkladığımızda popUp ı görebiliyoruz.
          if(evt.isPopupTrigger()){
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel3MouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //Önceki sayfaya geri dönüyor.
        KayıtVeGiris kayitGiris=new KayıtVeGiris();
        kayitGiris.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void baglan() {
        try {
            System.out.println("Başardık");

            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Mysql connector yok");
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adSoyad_field;
    private javax.swing.JTextField ara_field;
    private javax.swing.JSpinner doz_spinner;
    private javax.swing.JButton guncel_button;
    private javax.swing.JTextField ilacFiyat_field;
    private javax.swing.JTextField ilacFiyati_field;
    private javax.swing.JLabel ilacLabel;
    private javax.swing.JTable ilacSatısTablosu;
    private javax.swing.JComboBox<String> ilac_comboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydet_button;
    private javax.swing.JButton sil_btn;
    private javax.swing.JTextField tcNo_field;
    // End of variables declaration//GEN-END:variables
}
