/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import javax.swing.table.TableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author User-Pc
 */
public class İlacListesi extends javax.swing.JFrame {
      private String kullaniciAdi = "root";
    private String parola = "";
    private String host = "localhost";
    private String dtb = "hasta";
    private int port = 3306;
    private Connection conn=null;
    private String dtb2="sistemegiris";
    /**
     * Creates new form İlacListesi
     */
    public İlacListesi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        kullanım_field = new javax.swing.JTextArea();
        kullanım = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ilacAdi_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stok_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ilacKodu_field = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        kullanim_field = new javax.swing.JTextArea();
        kaydet_button = new javax.swing.JButton();
        sil_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ilacTable = new javax.swing.JTable();

        kullanım_field.setColumns(20);
        kullanım_field.setRows(5);
        jScrollPane2.setViewportView(kullanım_field);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/previous.png"))); // NOI18N
        jLabel1.setText("GERİ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setText("İlaç Adı");

        ilacAdi_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilacAdi_fieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Kullanımı");

        jLabel5.setText("Stok");

        jLabel6.setText("Kodu");

        kullanim_field.setColumns(20);
        kullanim_field.setRows(5);
        jScrollPane3.setViewportView(kullanim_field);

        kaydet_button.setBackground(new java.awt.Color(153, 153, 0));
        kaydet_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kaydet_button.setText("KAYDET");
        kaydet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydet_buttonActionPerformed(evt);
            }
        });

        sil_button.setBackground(new java.awt.Color(102, 102, 0));
        sil_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sil_button.setText("SİL");
        sil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(sil_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kaydet_button))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ilacKodu_field, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(ilacAdi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(stok_field, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(ilacAdi_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stok_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ilacKodu_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydet_button)
                    .addComponent(sil_button))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/prescription.png"))); // NOI18N
        jLabel2.setText("İLAÇ LİSTESİ VE BİLGİLERİ");

        ilacTable.setBackground(new java.awt.Color(102, 102, 0));
        ilacTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"AFINITOR® 5 mg tablet ", "Bir bardak suya (yaklaşık 30 mL içeren) gereken tablet(ler)i koyun • Tablet(ler) parçalanana kadar nazikçe karıştırın ve derhal için • Bardağı aynı miktarda su ile (yaklaşık 30 mL) çalkalayın ve AFINITOR dozunun tamamını almanızı sağlamak üzere hepsini için. Tabletleri çiğnemeyiniz veya parçalamayınız.", "25", "A-424"},
                {"ALOMIDE® % 0.1 steril göz damlası", "Göz kapağı ve gözünüz arasında bir kese oluşacak kadar, parmağınızla alt göz kapağınızı aşağı doğru çekiniz", "40", "A-425"},
                {"AZARGA®", "Yetişkinlerde normal doz, göze veya gözlere, sabah ve akşam olmak üzere, günde iki kez, birer damladır. Sadece doktorunuz önerdiği zaman AZARGA®'yı yalnızca gözlerinize kullanınız. ", "25", "A-426"},
                {"AZOPT® %1 Steril Göz Damlası", "AZOPT göze damlatılarak kullanılır. Ürünü başka bir yolla kullanmayınız. Ürün önerildiği şekilde kullanıldığı takdirde, besinlerle ve içeceklerle bir ilişkisi yoktur. lacı kullanmadan önce doktorunuza veya eczacınıza danışınız.", "50", "A-427"},
                {"BETOPTIC® %0.5 ", "Genellikle günde 2 kez hasta göze veya gözlere bir damla olacak şekilde uygulanır. Ancak, sizin özel durumunuza uygun olarak doktorunuzun dozu değiştirmesi olasıdır. BETOPTIC'i yalnızca gözlerinize uygulayınız", "42", "B-500"},
                {"BETOPTIC® S %0.25", "vvjvn", "12", "B-501"},
                {"CERTICAN®", "CERTICAN yalnızca ağızdan kullanım içindir. miligramdır. Tabletlerin erimesi için 2 dakika bekleyiniz ve içmeden önce hafifçe karıştırınız. Bardağı 25 ml suyla durulayınız ve bu suyu tamamen içiniz.", "25", "C-700"},
                {"CO-DİOVAN®", "CO-DIOVAN aç karnına ya da besinlerle birlikte alınabilir. Doktorunuz izin verinceye kadar alkol kullanmayınız. Alkol, kan basıncınızın daha fazla düşmesine ve/veya başınızın dönmesine ya da bayılmanıza neden olabilir. İlacı kullanmadan önce doktorunuza veya eczacınıza danışınız.", "35", "C-701"},
                {"EXELON®", "Bu kullanma talimatında yer alan bilgilerden farklı bile olsalar doktorunuz tarafından size verilen tüm talimatları dikkatle izleyiniz. Önerilen dozu aşmayınız", "14", "E-800"},
                {"EXFORGE® ", "EXFORGE, sadece ağızdan kullanım içindir. Aç karnına ya da besinlerle birlikte alabilirsiniz. Tableti bir bardak su ile yutunuz", "20", "E-802"},
                {"EXJADE®", "Her bir suda dağılan tablet 500 mg deferasiroks içerir. EXJADE tabletler 28 tablet içeren blister ambalajlarda sunulmaktadır.", "30", "E-803"},
                {"FEMARA® ", "FEMARA sadece ağızdan kullanım içindir. Tableti aç ya da tok karnına alabilirsiniz. Tabletleri tercihen her gün aynı saatte bir bardak su ile yutunuz. ", "8", "F-900"},
                {"FLAREX®", "FLAREX göze damlatılarak kullanılır. Ürünü başka bir yolla kullanmayınız. Ürün önerildiği şekilde kullanıldığı takdirde, besinlerle ve içeceklerle bir ilişkisi yoktur.", "20", "F-902"},
                {"GALVUS MET® ", "Genel GALVUS MET dozu günde bir ya da iki tablettir. Günde iki tableti geçmeyiniz.", "25", "G-1000"},
                {"JAKAVI®", "JAKAVI'yi her gün aynı saatte almalısınız. Aç veya tok karna alabilirsiniz.  Tabletleri bütün olarak bir bardak su ile yutunuz", "14", null}
            },
            new String [] {
                "İlaç Adı", "Kullanımı", "Stok", "Kodu"
            }
        ));
        ilacTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ilacTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ilacTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ilacAdi_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilacAdi_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ilacAdi_fieldActionPerformed

    private void ilacTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilacTableMouseClicked
        // TODO add your handling code here:
        //Önceden tabloya yazdığımız bilgileri table 'a tıklayarak soldaki fieldların içine yazabiliyoruz.
       int satirNo=ilacTable.getSelectedRow();
       TableModel model=ilacTable.getModel();
       ilacAdi_field.setText(model.getValueAt(satirNo,0).toString());
       kullanim_field.setText(model.getValueAt(satirNo,1).toString());
       stok_field.setText(model.getValueAt(satirNo,2).toString());
      ilacKodu_field.setText(model.getValueAt(satirNo,3).toString());
       
       
    }//GEN-LAST:event_ilacTableMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        IlacSatıs ilacSatıs=new IlacSatıs();
        ilacSatıs.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked
  DbBaglantiİlacOzellikleri ilacOzellik=new DbBaglantiİlacOzellikleri();
    private void kaydet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydet_buttonActionPerformed
   //Generic kullanarak ilacın adını getObj methodu sayesinde getirmiş oldu.
    String ilacAdi=ilacAdi_field.getText();
    MyGeneric<String>mg1=new MyGeneric<String>(ilacAdi);
    String obj=mg1.getObj();
     //   String ilacinAdi=ilacAdi_field.getText();
     //Gerekli parametreler kaydet metodunun içine yazılıp kaydedildi.
     String ilacinAdi=obj;
       String ilacKullanimi=kullanim_field.getText();
       String stok=stok_field.getText();
       String ilacKodu= ilacKodu_field.getText();
       ilacOzellik.kaydet(ilacinAdi, ilacKullanimi, stok, ilacKodu);
    }//GEN-LAST:event_kaydet_buttonActionPerformed

    private void sil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_buttonActionPerformed
     //Silinmek istenen ilaç sil metoduyla silinir. 
        String ilacAdi=ilacAdi_field.getText();
       String kullanim=kullanım_field.getText();
       String stok=stok_field.getText();
       String ilacKodu=ilacKodu_field.getText();
       ilacOzellik.sil(ilacAdi, kullanim, stok, ilacKodu);
    }//GEN-LAST:event_sil_buttonActionPerformed
 public void baglan(){
      try {
             System.out.println("Başardık");
             
            Class.forName("com.mysql.jdbc.Driver");
        } 
        catch (ClassNotFoundException e) {
            System.out.println("Mysql connector yok");
            e.printStackTrace();
        }
 }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ilacAdi_field;
    private javax.swing.JTextField ilacKodu_field;
    private javax.swing.JTable ilacTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kaydet_button;
    private javax.swing.JTextArea kullanim_field;
    private javax.swing.JLabel kullanım;
    private javax.swing.JTextArea kullanım_field;
    private javax.swing.JButton sil_button;
    private javax.swing.JTextField stok_field;
    // End of variables declaration//GEN-END:variables
}
