/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User-Pc
 */
public class KayıtVeGiris extends javax.swing.JFrame {

    ArrayList hastalar;
    DefaultListModel listModel = new DefaultListModel();
    private String kullaniciAdi = "root";
    private String parola = "";
    private String host = "localhost";
    private String dtb = "hasta";
    private int port = 3306;
    private Connection conn = null;

    /**
     * Creates new form KayıtVeGiriş
     */
    public KayıtVeGiris() {
        initComponents();
        hastalar = new ArrayList<>();
        arama_list.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jTextField6 = new javax.swing.JTextField();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dogumTarihi = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        tabbedPanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        girisTcNo_field = new javax.swing.JTextField();
        girisAdSoyad_field = new javax.swing.JTextField();
        eReceteNo_field = new javax.swing.JTextField();
        giris_button = new javax.swing.JButton();
        temizle_button = new javax.swing.JButton();
        girisKaydet_button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kayitTcNo_field = new javax.swing.JTextField();
        kayitAdSoyad_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kadin_radioButton = new javax.swing.JRadioButton();
        erkek_radioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        kaydolKaydet_button = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        arama_list = new javax.swing.JList<>();
        ara_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        hakkımızdaMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ses_checkBox = new javax.swing.JCheckBoxMenuItem();
        saglamlastir_radio = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        renk = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        jLabel9.setText("jLabel9");

        jTextField6.setText("jTextField6");

        jButton1.setText("jButton1");

        jLabel11.setText("jLabel11");

        jButton2.setText("jButton2");

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/cross.png"))); // NOI18N
        jMenuItem3.setText("Kapat");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setText("Kopyala");
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setText("Yapıştır");
        jPopupMenu1.add(jMenuItem5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tabbedPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabbedPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 102, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 51, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("T.C NO");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("AD SOYAD");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("E REÇETE NO");

        giris_button.setBackground(new java.awt.Color(153, 153, 0));
        giris_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        giris_button.setText("GİRİŞ");
        giris_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_buttonActionPerformed(evt);
            }
        });

        temizle_button.setBackground(new java.awt.Color(153, 153, 0));
        temizle_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        temizle_button.setText("TEMİZLE");
        temizle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizle_buttonActionPerformed(evt);
            }
        });

        girisKaydet_button.setBackground(new java.awt.Color(153, 153, 0));
        girisKaydet_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        girisKaydet_button.setText("KAYDET");
        girisKaydet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisKaydet_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temizle_button)
                .addGap(35, 35, 35))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(girisKaydet_button)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(giris_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(girisAdSoyad_field))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eReceteNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(girisTcNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(girisTcNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(girisAdSoyad_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(eReceteNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giris_button)
                    .addComponent(temizle_button)
                    .addComponent(girisKaydet_button))
                .addGap(23, 23, 23))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/pharmacy (4).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("GİRİŞ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 0));
        jPanel6.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tüm alanların doldurulması zorunludur.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("T.C Kimlik No");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ad Soyad");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Cinsiyet");

        kadin_radioButton.setBackground(new java.awt.Color(153, 153, 0));
        kadin_radioButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        kadin_radioButton.setText("Kadın");

        erkek_radioButton.setBackground(new java.awt.Color(153, 153, 0));
        erkek_radioButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        erkek_radioButton.setText("Erkek");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Doğum Tarihi");

        kaydolKaydet_button.setBackground(new java.awt.Color(102, 102, 0));
        kaydolKaydet_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kaydolKaydet_button.setText("KAYDET");
        kaydolKaydet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydolKaydet_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kayitTcNo_field, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(kayitAdSoyad_field, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(kadin_radioButton))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(erkek_radioButton)))
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(kaydolKaydet_button)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kayitTcNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kayitAdSoyad_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kadin_radioButton)
                    .addComponent(erkek_radioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(kaydolKaydet_button)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabbedPanel.addTab("KAYDOL", jPanel4);

        jPanel7.setBackground(new java.awt.Color(102, 102, 0));

        jScrollPane2.setViewportView(arama_list);

        ara_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ara_fieldKeyReleased(evt);
            }
        });

        jLabel12.setText("Hasta Ara");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ara_field, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(ara_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        tabbedPanel.addTab("ARA", jPanel7);

        getContentPane().add(tabbedPanel);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 0));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/entrance (1).png"))); // NOI18N
        jMenu1.setText("GERİ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu6.setText("ECZANEMİZ");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        hakkımızdaMenuItem.setText("Hakkımızda");
        hakkımızdaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakkımızdaMenuItemActionPerformed(evt);
            }
        });
        jMenu6.add(hakkımızdaMenuItem);

        jMenuBar1.add(jMenu6);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/folder.png"))); // NOI18N
        jMenu3.setText("DOSYA");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ses_checkBox.setText("Ses");
        ses_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ses_checkBoxActionPerformed(evt);
            }
        });
        jMenu3.add(ses_checkBox);

        saglamlastir_radio.setSelected(true);
        saglamlastir_radio.setText("Sağlamlaştır");
        saglamlastir_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saglamlastir_radioActionPerformed(evt);
            }
        });
        jMenu3.add(saglamlastir_radio);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/pallet.png"))); // NOI18N
        jMenu2.setText("TEMA");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Karanlık");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Aydınlk");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        renk.setText("Renklendir");
        renk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renkActionPerformed(evt);
            }
        });
        jMenu2.add(renk);
        jMenu2.add(jSeparator1);
        jMenu2.add(jSeparator2);

        jMenuItem6.setText("Ayarlar");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jPanel3.setBackground(Color.BLACK);
        jPanel4.setBackground(Color.BLACK);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jPanel3.setBackground(Color.WHITE);
        jPanel4.setBackground(Color.WHITE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void giris_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_buttonActionPerformed
        // Recete no ya sadece sayı yazılmasını belirten bir regex bulunuyor.
        String receteNo = eReceteNo_field.getText();
        Pattern p = Pattern.compile("^\\d+");
        Matcher m = p.matcher(receteNo);
        if (!m.matches()) {
            JOptionPane.showMessageDialog(null, " Recete No boşluğuna harf yazılmaz");
            return;
        }
        //Ad soyad ,tc ,recete no nun alanı boş bırakılırsa uyarı verir.
     if(girisAdSoyad_field.getText().isEmpty() || girisTcNo_field.getText().isEmpty() || eReceteNo_field.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Boş kalan alanları doldurunuz!!", "UYARI", JOptionPane.INFORMATION_MESSAGE);
            return;
     }
     //ilaç satış frame açılır ve bilgiler constructora yazılanlardan ötürü direk o sayfaya basılır.
        IlacSatıs ilacSatıs = new IlacSatıs(girisAdSoyad_field.getText(), girisTcNo_field.getText());
        ilacSatıs.setVisible(true);

    }//GEN-LAST:event_giris_buttonActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        //Sayfa kapatan bir metot
        EczaneIlacSatısSistemi ecz = new EczaneIlacSatısSistemi();
        ecz.setVisible(true);
        ecz.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenu1ActionPerformed

    Dbbaglanti baglanti = new Dbbaglanti();
    private void kaydolKaydet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydolKaydet_buttonActionPerformed
        // TODO add your handling code here:
  //Ad ve soyad da sadece harflerin kullanılması gerektiğini gösteren bir regex.
        String adSoyad = kayitAdSoyad_field.getText();
        Matcher matcher = Pattern.compile(".*\\d+.*").matcher(adSoyad);
        if (matcher.matches()) {
            JOptionPane.showMessageDialog(null, "Ad Soyad boşluğuna rakam yazılmaz");
            return;
        }

        if (kayitTcNo_field.getText().isEmpty() || kayitAdSoyad_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Boş kalan alanları doldurunuz!!", "UYARI", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String tc2 = kayitTcNo_field.getText();
        //Aşağıdaki metodu kontrol ederek hastanın kayıtlı olup olmadığını belirtiyor.
        if (baglanti.buHastaVarMi(tc2)) {
            JOptionPane.showMessageDialog(null, "Böyle bir hasta var.Tekrar kaydedilmez", "WARNİNG", JOptionPane.WARNING_MESSAGE);
        } else {
            String tc = kayitTcNo_field.getText();
            String ad = kayitAdSoyad_field.getText();

            String cinsiyet = "";
            if (kadin_radioButton.isSelected()) {
                cinsiyet = "Kadın";
            } else {
                cinsiyet = "Erkek";
            }
            //SimpleDateFormat sınıfını kullanarak stringe çevirdim.
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dogumTarihi = sdf.format(dateChooser.getDate());
            baglanti.kaydolKaydet(tc, ad, cinsiyet, dogumTarihi);

        }


    }//GEN-LAST:event_kaydolKaydet_buttonActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        EczaneIlacSatısSistemi e = new EczaneIlacSatısSistemi();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void girisKaydet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisKaydet_buttonActionPerformed
        // TODO add your handling code here:
        //tc boşluğunnun sayılardan ve 11 haneli olması gerektiğini gösteren bir regex.
        String tcNumara = girisAdSoyad_field.getText();

        Pattern p = Pattern.compile("\\d{10}[2468]");
        Matcher m2 = p.matcher(tcNumara);
        if (m2.matches()) {
            JOptionPane.showMessageDialog(null, "TC yazımında hata var");
            return;
        }

        String tc = girisTcNo_field.getText();
        if (baglanti.giristekiKisiAyniMi(tc)) {

            JOptionPane.showMessageDialog(null, "Kişi daha önce kayıt edilmis", "WARNİNG", JOptionPane.WARNING_MESSAGE);
        } else {
            String tcNo = girisTcNo_field.getText();
            String adSoyad = girisAdSoyad_field.getText();
            String eReceteNo = eReceteNo_field.getText();
            baglanti.girisKaydet(tcNo, adSoyad, eReceteNo);
        }

    }//GEN-LAST:event_girisKaydet_buttonActionPerformed

    private void temizle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizle_buttonActionPerformed
     //Silinmesini istediğimiz kişinin tc numarasını girerek databaseden silebiliyoruz. 
        String tc = girisTcNo_field.getText();
        String adSoyad = girisAdSoyad_field.getText();
        baglanti.temizle(tc, adSoyad);


    }//GEN-LAST:event_temizle_buttonActionPerformed

    private void renkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renkActionPerformed

        if (evt.getSource() == renk) {
            //Aşağıda seçim yapmak istiyorsa veya istemiyorsa diye 2 seçenekli JOptionPane yazdım.Değiştirmek istiyorsa sayfanın rengini değiştirebilecek ,istemiyorsa seçim yapamayacak.
            int secim = JOptionPane.showConfirmDialog(null, "Renk Seçmek İstiyor Musunuz?", "BİLGİLENDİRME", JOptionPane.OK_CANCEL_OPTION);
            if (JOptionPane.CANCEL_OPTION == secim) {
                return;
            } else {
                JColorChooser colorChooser = new JColorChooser();
                Color color = JColorChooser.showDialog(null, "Bir renk seçin", Color.BLACK);
                jPanel4.setBackground(color);
                kayitTcNo_field.setForeground(color);
                Color color2 = JColorChooser.showDialog(null, "Bir renk seçin", Color.BLACK);
                jPanel5.setBackground(color2);
            }

        }
    }//GEN-LAST:event_renkActionPerformed

    private void ses_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ses_checkBoxActionPerformed

        if (ses_checkBox.isSelected()) {
            JOptionPane.showMessageDialog(null, "Sessize alındı");
        }
    }//GEN-LAST:event_ses_checkBoxActionPerformed

    private void ara_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ara_fieldKeyReleased
        // TODO add your handling code here:
   //Herhangi bir harf girildiğinde hastanın daha önce kayıtlı olup olmadığını buluyor.İlgili harf yazıldığında hastaya ulaşılabiliyor.
        listModel.removeAllElements();
        String ara = ara_field.getText();
        baglanti.ismiXIleBaşlayanHastalar(ara, hastalar);
        for (int i = 0; i < hastalar.size(); i++) {
            listModel.addElement(hastalar.get(i));
        }
    }//GEN-LAST:event_ara_fieldKeyReleased

    private void hakkımızdaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakkımızdaMenuItemActionPerformed
        // TODO add your handling code here:
        Hakkımızda hakkımızda = new Hakkımızda();
        hakkımızda.setVisible(true);
        dispose();
    }//GEN-LAST:event_hakkımızdaMenuItemActionPerformed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        // TODO add your handling code here:
        //Sağa tıklanıldığında popUp ı görmemizi sağlıyor.
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel3MouseReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void saglamlastir_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saglamlastir_radioActionPerformed
        // TODO add your handling code here:
        if (saglamlastir_radio.isSelected()) {
            JOptionPane.showMessageDialog(null, "Alt yapı sağlamlaştırıldı");
        }
    }//GEN-LAST:event_saglamlastir_radioActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ara_field;
    private javax.swing.JList<String> arama_list;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dogumTarihi;
    private javax.swing.JTextField eReceteNo_field;
    private javax.swing.JRadioButton erkek_radioButton;
    private javax.swing.JTextField girisAdSoyad_field;
    private javax.swing.JButton girisKaydet_button;
    private javax.swing.JTextField girisTcNo_field;
    private javax.swing.JButton giris_button;
    private javax.swing.JMenuItem hakkımızdaMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton kadin_radioButton;
    private javax.swing.JButton kaydolKaydet_button;
    private javax.swing.JTextField kayitAdSoyad_field;
    private javax.swing.JTextField kayitTcNo_field;
    private javax.swing.JMenuItem renk;
    private javax.swing.JRadioButtonMenuItem saglamlastir_radio;
    private javax.swing.JCheckBoxMenuItem ses_checkBox;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JButton temizle_button;
    // End of variables declaration//GEN-END:variables
}
